name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - jferrl
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternatives I've considered include [...]
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your use case and how this feature would benefit you and other users.
      placeholder: This feature would help me [...]
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: If you have ideas on how to implement this feature, please share them.
      placeholder: This could be implemented by [...]
    validations:
      required: false

  - type: textarea
    id: code-example
    attributes:
      label: Code example
      description: If applicable, provide a code example of how you envision the feature working.
      render: go
      placeholder: |
        package main
        
        import "github.com/jferrl/go-githubauth"
        
        func main() {
          // Example usage of new feature
        }

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information that might help us understand the request.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
